import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBarNavigationMain from "@/components/Navigation/TopBarNavigationMain";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard notaria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBarNavigationMain/>
        {children}
        
        <ToastContainer
          position="bottom"
        />
      </body>
    </html>
  );
}
