import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBarNavigationMain from "@/components/Navigation/TopBarNavigationMain";
import { ToastContainer } from "react-toastify";
import EditorContext from "@/context/ConextEditor";
import ContratoContext from "@/context/ContratosContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard notaria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`font-poppins text-[#0C1019]`}
      >
        <EditorContext>
          <ContratoContext>
          <TopBarNavigationMain/>
          {children}
          
          <ToastContainer
            position="bottom"
          />
          </ContratoContext>
        </EditorContext>
      </body>
    </html>
  );
}
